name: Terraform-AWS-Destroy-Infrastructure

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment (dev, qa, uat, prod)"
        required: true
        default: "prod"
      region:
        description: "AWS Region"
        required: true
        default: "us-east-2"

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    env:
      TF_ENV: ${{ github.event.inputs.environment }}
      AWS_REGION: ${{ github.event.inputs.region }}
      TF_DIR: ${{ github.event.inputs.environment }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Overwrite config with empty file to force destroy
        run: |
          echo "# Empty Terraform config to force destroy" > $TF_DIR/main.tf

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -backend-config="key=${{ env.TF_ENV }}/terraform.tfstate"

      - name: Terraform Destroy
        working-directory: ${{ env.TF_DIR }}
        run: terraform destroy -auto-approve -lock=false
