- name: Temporarily move Terraform configs
    run: |
    mkdir ../backup && mv $TF_DIR/*.tf ../backup/

- name: Terraform Init
  working-directory: ${{ env.TF_DIR }}
  run: terraform init -backend-config="key=${{ env.TF_ENV }}/terraform.tfstate"

- name: Terraform Destroy
  working-directory: ${{ env.TF_DIR }}
  run: terraform destroy -auto-approve -lock=false
